### ISSUE TITLE
mqtt.birthAndWill not updated during long-term interface failure

### ISSUE THREAD

**Issue by pfeffix** [gkiefer/home2l#5]
If the bus connection gets lost and recovering isn't successful, the `mqtt.birthAndWill` topic is not updated and stays in `online` state.
The brownie device status topics are correctly set to `?`, during the connection lost.
If I manually stop the home2l-server, the `mqtt.birthAndWill` topic gets the correct `offline` value.
I use the latest home2l release with an ELV USB-I2C adapter on amd64 hardware with Debian 11.

home2l.conf:
`mqtt.birthAndWill = status:offline:online`

Debug logs:
```
home2l[448]: [home2l-server] DEBUG-1 (/brownies/brownies.C:2346): /dev/ttyUSB0: Not a socket: /dev/ttyUSB0 .  
home2l[448]: [home2l-server] DEBUG-1 (/brownies/brownies.C:2672): /dev/ttyUSB0: Interface problem (received neither ACK nor NACK)
home2l[448]: [home2l-server] WARNING (/brownies/brownies.C:2838): /dev/ttyUSB0: Bus connection lost: Recovering.
home2l[448]: [home2l-server] DEBUG-1 (/brownies/brownies.C:2346): /dev/ttyUSB0: Not a socket: /dev/ttyUSB0 .
home2l[448]: [home2l-server] DEBUG-1 (/brownies/brownies.C:2672): /dev/ttyUSB0: Interface problem (received neither ACK nor NACK)
home2l[448]: [home2l-server] WARNING (/brownies/brownies.C:2838): /dev/ttyUSB0: Bus connection lost: Recovering.
home2l[448]: [home2l-server] DEBUG-1 (/brownies/brownies.C:2346): /dev/ttyUSB0: Not a socket: /dev/ttyUSB0 .
home2l[448]: [home2l-server] DEBUG-1 (/brownies/brownies.C:2672): /dev/ttyUSB0: Interface problem (received neither ACK nor NACK)
home2l[448]: [home2l-server] WARNING (/brownies/brownies.C:2838): /dev/ttyUSB0: Bus connection lost: Recovering.
...continues with same messages
```

**Comment by gkiefer** [comment]
For what I can see, the shown behavior is intended and correct. The Home2Ls generally report failures on a resource basis by reporting an "unknown" state seen as "?" in MQTT messages. The  purpose of the birth-and-will topic is to make a general failure of the whole Home2L cluster (or the MQTT bridge) detectable by subscribers, in which case no "unknown" states can be reported anymore.

In your case, only the Brownie bus failed, but not the complete Home2L server, which may still serve other resources as well.

**Comment by pfeffix** [comment]
Thanks for the explanation, now it makes sense to me.
